### ISSUE TITLE
Баги и недочёты слайдера

### ISSUE THREAD

**Issue by a-poluhin** [PsarewIvan/fsd-task-4#1]
Нужно обновлять текущее значение, когда меняешь максимальное или минимальное значение текущие значения не должны ограничивать изменения. Например текущее значение 770 пытаемся изменить максимально возможное значение с 1000 на 700, а макс. значение хоп и делается 770=)
![curr-value-affect-on-change-max-value ](https://user-images.githubusercontent.com/10168007/118099991-26452f00-b400-11eb-96ff-9986c83c66a6.gif)

Через инпут можно ввести значение не удовлетворяющее условиям шага
![image](https://user-images.githubusercontent.com/10168007/118100990-4d503080-b401-11eb-84ae-6a46239221bf.png)

**Comment by PsarewIvan** [comment]
С максимальным значением - я бы назвал это - не баг а фича =) я помню долго ломал голову, чтобы сделать именно так =) придется обратно править )

**Comment by a-poluhin** [comment]
> С максимальным значением - я бы назвал это - не баг а фича =) я помню долго ломал голову, чтобы сделать именно так =) придется обратно править )

Вот так всегда стараемся как лучше=)

**Comment by PsarewIvan** [comment]
Вроде все починил. Повозился, но вышло ниче так :)
![Screen Recording 2021-05-19 at 19 36 06](https://user-images.githubusercontent.com/28845333/118852066-16838a00-b8db-11eb-84be-5b8adf8abd29.gif)
![Screen Recording 2021-05-19 at 19 39 28](https://user-images.githubusercontent.com/28845333/118852093-1e432e80-b8db-11eb-8598-699aabc32263.gif)
![Screen Recording 2021-05-19 at 19 36 06](https://user-images.githubusercontent.com/28845333/118852100-20a58880-b8db-11eb-878c-6dec70bb53ad.gif)

**Comment by a-poluhin** [comment]
С верхним все круто=)
Чет я сначала не обратил внимание: Добавь чтобы текущее значение автоматически подгонялось под ближайшее значение актуальное для введенного шага
![image](https://user-images.githubusercontent.com/10168007/119355912-018a6a80-bcd0-11eb-8c2c-7b4c3c130375.png)
